volumes:
  postgres_data:

networks:
  default:
    name: ontrack_network
    driver: bridge

services:
  db:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=ontrack'
      - 'POSTGRES_USER=default'
      - 'POSTGRES_PASSWORD=demo'
    ports:
      # Expose Port for DB client to connect
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: gradle:8.13-jdk21-alpine
    working_dir: /app
    restart: always
    depends_on:
      - db
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ontrack'
      - 'SPRING_DATASOURCE_USERNAME=default'
      - 'SPRING_DATASOURCE_PASSWORD=demo'
    ports:
      - "8080:8080"
      # 5005 is used for debug listener
      - "5005:5005"
    command: gradle bootRun --no-daemon
    volumes:
      - .:/app
