name: OnTrack Deployment Workflow
on:
  push:
    branches:
      - 'develop'
    paths:
      - 'backend/**'
  workflow_dispatch:

permissions:
  contents: read

# Prevent multiple pipelines running at the same time on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/on-track:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/on-track:latest
#
#  migrate-db:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Run DB migrations (add new schema elements)
#        env:
#          DB_URL: ${{ secrets.DB_URL }}
#          DB_USERNAME: ${{ secrets.DB_USERNAME }}
#          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#        run: |
#          liquibase --url=${DB_URL} --username=${DB_USERNAME} --password=${DB_PASSWORD} update
